simpleList =("red","Green","blue",9,8,7)
print(simpleList)
print(type(simpleList))
print("simpleList[1]=",(simpleList[1]))
print("simpleList[1]=",(simpleList[4]))
print(type(simpleList[4]))
print("simpleList[0:3]=",(simpleList[0:3]))
print("simpleList[3:]=",(simpleList[3:]))